### ISSUE TITLE
Update local development and CI to use kcp test server commands

### ISSUE THREAD

**Issue by mikenairn** [kcp-dev/kcp-glbc#328]
Priority: Low

## Issue Description

We currently run kcp [here](https://github.com/Kuadrant/kcp-glbc/blob/main/utils/local-setup.sh#L156) for local development and [here]( https://github.com/Kuadrant/kcp-glbc/blob/main/.github/workflows/e2e.yaml#L131 ) for the e2e tests. We should change this to work more how kcp do it and use the built in test-server binaries in kcp `bin/test-server`. It would also be good if we can optionally use the `bin/sharded-test-server` command as well which would give an environment closer to that of a production kcp instance. 

Another option worth looking into, is can we have it run with a "user" context `go run ./cmd/kcp start --batteries-included="+user"`, which might also help when we are trying to debug issues, and want to work against a local kcp as a user would.

Note: This gives a more consistent admin user setup, and so will help if/when we switch to using home workspaces.

**Comment by ChristianZaccaria** [comment]
WIP - @mikenairn and I agreed that further investigation and discussion is required

https://github.com/Kuadrant/kcp-glbc/compare/main...ChristianZaccaria:kcp-glbc:kcp_test_server

It fails when it's trying to open a file that is originally part of KCP repo, however if we create test/e2e/framework/auth-tokens.csv file it will run.
