### ISSUE TITLE
Implement routes using abstraction layer

### ISSUE THREAD

**Issue by philbrookes** [kcp-dev/kcp-glbc#392]
Routes are reconciled by HCG and processed for custom host validation, generated host replacement and workload migration.

## custom hosts enabled
- If the custom domain is not yet verified, the route will have it's host modified in place.
- If the custom domain is verified, the route will be "shadowed" to a second ingress in order to maintain the generated host which will have an owner ref of the original route.
## custom hosts disabled
- The routes are updated with a generated host

## Advanced scheduling
Confirm migration of workloads using routes still functions, and make changes as required.

## e2e tests
covered in #401

**Comment by maleck13** [comment]
can you add a bit more detail as to what this part is?
