### ISSUE TITLE
Use DNSRecord DNSName as the host value for ingress

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp-glbc#412]
**What**

We currently have a very flimsy mechanism for storing our generated host. The annotation on the Ingress is something that can be removed or changed by an end user. We want to protect from any form of tampering with this host. Rather than using the ingress annotation as the "source of truth" for what host we have generated, we should move to using the DNSRecord as this is our API and in the future we will be able to dictate via an APIExport what end users can do with that resource. 

We want a flow that does the following

- check if there is a DNSRecord created for an ingress
- if it exists, ensure that the annotation added to the ingress is of the value that is in the DNSrecord DNSName
- if it doesn't exist, create an empty DNSRecord with no targets but a defined DNSName add this as the host for the ingress
- 
Current DNSRecord requires at least one target to be set, we would change this to allow none. our DNS reconciler would add logic to not update AWS until at least one target exists .

We would need to update everywhere using the annotation to use a look dnsName method

**Comment by makslion** [comment]
is followed by #500
