### ISSUE TITLE
Host watcher continually tries to get records for unreachable host

### ISSUE THREAD

**Issue by mikenairn** [kcp-dev/kcp-glbc#462]
Priority: Low/Medium/High (choose one, remove the other options)

## Expected Behaviour
* TBD, but shouldn't keep printing log statements and trying continually to lookup the IP

## Actual Behaviour

Host Watcher can fall into a loop of continuously trying to get the IPs for a host that does not resolve:

```
2022-10-11T07:59:45.001Z ERROR kcp-glbc-ingress/glbc.host-watcher runtime/asm_amd64.s:1571 Failed to lookup IP address {"key": "****", "host": "<somehost>", "error": "no records found for host"}
``` 

### Steps to Reproduce the Problem

1. Run local-setup using a CRC cluster (make local-setup USE_CRC=true)
2. Create the echo sample service
3. Stop the crc cluster
4. Look at the logs (Note this will happen for every DNSRecord pointing at that same cluster, so the more there are, the more logs there will be)

## Suggested Resolution
*

## Additional Information

*

**Comment by maleck13** [comment]
We probably want to handle this error and perform some form of back off before dropping it entirely
